// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84S8lsNeh3NwEKLUjxVRzcBqYKxP7nP0',
    appId: '1:396785971772:web:6e11948a7b08227a778939',
    messagingSenderId: '396785971772',
    projectId: 'education-27652',
    authDomain: 'education-27652.firebaseapp.com',
    storageBucket: 'education-27652.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtFphPL2gGzwLHvZRO8Dfh8kAJoZW_ays',
    appId: '1:396785971772:android:528c19d2bc92b923778939',
    messagingSenderId: '396785971772',
    projectId: 'education-27652',
    storageBucket: 'education-27652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGX9GXiE9MqBQ1SzhhrD3m_pPhCRDyN-w',
    appId: '1:396785971772:ios:7b1148cadd71fdcd778939',
    messagingSenderId: '396785971772',
    projectId: 'education-27652',
    storageBucket: 'education-27652.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGX9GXiE9MqBQ1SzhhrD3m_pPhCRDyN-w',
    appId: '1:396785971772:ios:024ff6ee80d3e30f778939',
    messagingSenderId: '396785971772',
    projectId: 'education-27652',
    storageBucket: 'education-27652.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
